### ISSUE TITLE
Improvement : moving the menu

### ISSUE THREAD

**Issue by thiblizz** [emilyinure/solace-csgo#13]
Hey,

@emilyinure After you resolved the other issues I mentioned previously (all related to the menu).

It should be great to maybe don't allow the window to be dragged out of the game window, so you cannot access it anymore.
Currently, menu out of bounds = cannot drag it anymore.

2 options, you take the better one:

- Make the menu, so it cannot be dragged out of the game window, like some shadow padding (top, bottom, right, left), then the menu cannot be dragged further.
- Make the menu, so it can be dragged from bottom, right and left (not only top), so it can be re-dragged to the game window.

The first option should be the proper one, I guess.

Regards,

**Comment by emilyinure** [comment]
Done!
