### ISSUE TITLE
Improvement : keyboard input

### ISSUE THREAD

**Issue by thiblizz** [emilyinure/solace-csgo#14]
@emilyinure Currently, only mouse input is not captured outside the game window, but keyboard input is still captured while you are on Windows and you could unintentionally unhook your cheat or even display the menu just by pressing keys, this is an unwanted/unnecessary behavior.

Regards,

**Comment by emilyinure** [comment]
I've fixed it but I ended up having to just check the focused window whenever scanning input.
Wndproc was having some issues where keyboard input was delayed or not received at all.
Wndproc is still used for mouse input as for some reason there's no delay or missed input for that.
