### ISSUE TITLE
Non-existent index in ClassId

### ISSUE THREAD

**Issue by thiblizz** [emilyinure/solace-csgo#25]
https://github.com/emilyinure/solace-csgo/blob/210a1c4b865a3f5c0af622a832a2ac1bcca26662/solace-csgo/base_client.h#L354

@emilyinure, I just dumped server class infos, and this one doesn't exist.

**Comment by emilyinure** [comment]
I've updated the classids since then locally. All of them have been off up until now. I'm prepping big changes to the repo so expect to wait a bit longer for the next push
