### ISSUE TITLE
IsTickValid improvements

### ISSUE THREAD

**Issue by codecheck01** [emilyinure/solace-csgo#5]
https://github.com/emilyinure/solace-csgo/blob/f28a1531a7e047999e0437ad5bed6727ea8f9e45/solace-csgo/player_manager.cpp#L32

1. It should use server time.
2. It should account for deadtime.
3. It should account for view interpolation (correctly).

Regards,

**Comment by emilyinure** [comment]
it is using servertime.
im unsure what you mean by deadtime, ill look into this though.
the fixes for view interpolation will be pushed soon

**Comment by emilyinure** [comment]
Soo, I don't believe that view interpolation actually does anything on the server, logging player vars in postdataupdate gets everything before its interpolated. All the data is clean and we're using/calculating lerptime the way that the server is. 
I'm seeing this post you took most of this from but, using servertime does compensate for deadtime(meaning the latency/delay between data transfers)

**Comment by emilyinure** [comment]
ah okay yes ive found it

**Comment by emilyinure** [comment]
update pushed
