### ISSUE TITLE
Todo clean up (grenade pred not implemented yet)

### ISSUE THREAD

**Issue by codecheck01** [emilyinure/solace-csgo#6]
https://github.com/emilyinure/solace-csgo/blob/852afc9de9620a32ae8f82acb524586808d43c23/solace-csgo/hooks.cpp#L18
https://github.com/emilyinure/solace-csgo/blob/852afc9de9620a32ae8f82acb524586808d43c23/solace-csgo/hooks.cpp#L322
https://github.com/emilyinure/solace-csgo/blob/852afc9de9620a32ae8f82acb524586808d43c23/solace-csgo/solace-csgo.vcxproj.filters#L259

So it compiles.

**Comment by emilyinure** [comment]
Fixed, apologies
